### ISSUE TITLE
Create GitHub workflows

### ISSUE THREAD

**Issue by ricortiz** [erleben/OpenTissue#23]
- [ ] PR labeler
Here are the possible labels:
```
type:Compiler:
    title: "^COMP:.*"

type:Bug:
    title: "^BUG:.*"

area:Documentation:
    title: "^DOC:.*"

type:Enhancement:
    title: "^ENH:.*"

type:Performance:
    title: "^PERF:.*"

type:Style:
    title: "^STYLE:.*"
```

- [ ] Apply clang-format

```
name: Apply clang-format to PR

on:
  pull_request:
    types: [labeled]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - uses: OpenTissue/OTITKApplyClangFormatAction@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
```

- [ ] Linter
```
name: clang-format linter

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: OpenTIssue/OTClangFormatLinterAction@master
      with:
        error-message: 'Code is inconsistent with OpenTissue Coding Style. Add the *action:ApplyClangFormat* PR label to correct.'
```
